from .extensions import ma
from .models import Post, User

from marshmallow import fields


# schema for the Post model auto generated by marshmallow
class PostSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Post
        load_instance = True


post_schema = PostSchema()
posts_schema = PostSchema(many=True)


# schema for the user with added password field to add the password before hashing, excluding password hash from the schema
class UserSchema(ma.SQLAlchemyAutoSchema):
    password = fields.String(load_only=True, required=True)

    class Meta:
        model = User
        load_instance = True
        exclude = ("password_hash",)


user_schema = UserSchema()
users_schema = UserSchema(many=True)
